fatal: [vac10webar1820.va.gov]: FAILED! => {"changed": true, "cmd": "cd \"/opt/tmp/ars-build-artifacts\"\ngit add .\ngit commit -m \"ars_promoteBuildArtifacts-ARS-Release-v2.4.3_candidate1\"\ngit tag -a ARS-Release-v2.4.3_candidate1 -m \"Tagging artifacts with version ARS-Release-v2.4.3_candidate1\"\ngit push origin PEDI-33881_staging_artifact_testing --tags\n", "delta": "0:00:04.653193", "end": "2025-04-22 14:58:50.403619", "msg": "non-zero return code", "rc": 1, "start": "2025-04-22 14:58:45.750426", "stderr": "fatal: tag 'ARS-Release-v2.4.3_candidate1' already exists\nTo https://github.com/department-of-veterans-affairs/ars-build-artifacts\n * [new tag]         ARS-Release-v2.4.1 -> ARS-Release-v2.4.1\n * [new tag]         ARS-Release-v2.4.3 -> ARS-Release-v2.4.3\n * [new tag]         ARS-Release-v2.4.3_candidate1 -> ARS-Release-v2.4.3_candidate1\n ! [rejected]        PEDI-33881_staging_artifact_testing -> PEDI-33881_staging_artifact_testing (fetch first)\nerror: failed to push some refs to 'https://github.com/department-of-veterans-affairs/ars-build-artifacts'\nhint: Updates were rejected because the remote contains work that you do not\nhint: have locally. This is usually caused by another repository pushing to\nhint: the same ref. If you want to integrate the remote changes, use\nhint: 'git pull' before pushing again.\nhint: See the 'Note about fast-forwards' in 'git push --help' for details.", "stderr_lines": ["fatal: tag 'ARS-Release-v2.4.3_candidate1' already exists", "To https://github.com/department-of-veterans-affairs/ars-build-artifacts", " * [new tag]         ARS-Release-v2.4.1 -> ARS-Release-v2.4.1", " * [new tag]         ARS-Release-v2.4.3 -> ARS-Release-v2.4.3", " * [new tag]         ARS-Release-v2.4.3_candidate1 -> ARS-Release-v2.4.3_candidate1", " ! [rejected]        PEDI-33881_staging_artifact_testing -> PEDI-33881_staging_artifact_testing (fetch first)", "error: failed to push some refs to 'https://github.com/department-of-veterans-affairs/ars-build-artifacts'", "hint: Updates were rejected because the remote contains work that you do not", "hint: have locally. This is usually caused by another repository pushing to", "hint: the same ref. If you want to integrate the remote changes, use", "hint: 'git pull' before pushing again.", "hint: See the 'Note about fast-forwards' in 'git push --help' for details."], "stdout": "On branch PEDI-33881_staging_artifact_testing\nYou are in a sparse checkout with 28% of tracked files present.\n\nnothing to commit, working tree clean", "stdout_lines": ["On branch PEDI-33881_staging_artifact_testing", "You are in a sparse checkout with 28% of tracked files present.", "", "nothing to commit, working tree clean"]
